### ISSUE TITLE
2.5.2 Pointer Cancellation

### ISSUE THREAD

**Issue by KaneCheshire** [theappbusiness/accessibility-guidelines#12]
The summary for this on the overview page is:

>Controls do not make things happen as soon as they are touched.

While the title on the detail is:

>2.5.2 Pointer Cancellation

Which feels a bit disconnected.

I'm also wondering if it should also mention being able to cancel the touch-down event by sliding your finger or mouse away from the element that was clicked or tapped?

**Comment by jfhector** [comment]
What about this?

* [Touch or click activation]() Make sure that custom buttons or links do not fire as soon as they are touched, so that users can slide their finger or mouse away to cancel the action.
