### ISSUE TITLE
Whether and how to tag each requirement with 'Design', 'Code' and 'Content'

### ISSUE THREAD

**Issue by jfhector** [theappbusiness/accessibility-guidelines#17]
Here's a situation of struggle that I've witnessed, as a Agile Delivery Lead used our checklist today:

#### Situation of struggle:

“I struggle when I read something that I don’t understand. I want to know whether this requirement is about something ‘under the hood’ that I’m not meant to understand, or something that’s within my realm but I’m not getting it."

##### In other words:

“Highlight what’s engineering stuff, so that people who are not engineer don’t feel intimidated by the document when understand some of this engineering stuff”.

#### Conclusion:

So, although I’d rather not assign roles to requirements right now, in our overview page, on our own (i.e. without consultation, buy-in and ownership with the different CoPs), I think that we could try to use language like “Design” and “Code” (and maybe just that) to indicate what each bullet point is about.

… even if we end up with both “design” and “code” being indicated for most bullet point. (At least, for the few are code, we avoid the situation of struggle above, and we avoid putting off non-tech people)

**Comment by jfhector** [comment]
@KaneCheshire I've [tagged each requirement with "Design", "Code and / or "Content" in this branch](https://github.com/theappbusiness/accessibility-guidelines/tree/Design-and-code-tags-test).

#### Here's what I learnt:

* (Assuming we're using markdown rather than HTML, and hence no custom styling): Just "Design", "Code" and / or "Content" as words after each requirement doesn't work visually. It makes the doc look very dull, and not easy to scan. It makes each requirement look longer.
* After adding these words ("Design", "Code" and / or "Content") in the left column of a table, it can see the usefulness of having this information. It makes the document much easier to scan, and feel less daunting.
* ... but using tables like this, and without being able to style these words using different colours or smaller font size, makes the document much more dull, and look more complicated. Compare with what's on master and tell me what you think.

#### Conclusions (for now):

* I believe that yes, it is useful to tag each requirement with "Design", "Code and / or "Content".
* But I really don't like how the table makes me feel – and how I imagine it's going to make readers feel. It feels so much less approachable, simple and human than the simple list we had before.
* I'm tempted to move to html for the overview page, so that we can use styles. In that case, I'd probably go back to the simple bullet point list, and add "Design", "Code and / or "Content" as [little badges](https://getbootstrap.com/docs/4.0/components/badge/#contextual-variations) within each bullet point (at the end, after a line break).

I'd love to know what you think (about all these things).

Re. HTML: We don't need to switch to HTML now, but I'd like to know what you think about the idea to eventually rendering using super simple HTML so that we can make things a bit nicer.

**Comment by jfhector** [comment]
#### I'm for HTML and styling

I do think that we should eventually move over to HTML – very basic plain HTML and no scripts so that no one feels daunted by it – and use some styling. 

For example, the badges could be to the left of text, where the current bullet points are (rather than after the text). In HTML this would all be in a table so it's accessible, but visually we could style this table so that it doesn't feel like one. (And get rid of the headers).

Super rough visual test for these badges in Google Docs:
<img width="217" alt="Screenshot 2019-08-14 at 21 38 39" src="https://user-images.githubusercontent.com/30028540/63054519-e7591100-bedb-11e9-9008-dc8978aff7a7.png">

#### But I don't think that we should get into any of this now

I'm for highlighting "Design", "Code" and "Content" on the overview doc, and using basic HTML and styling ...

... but the more I think about it, the more I believe that we should not bother ourselves with any of this now.

Yes the overview page will highlight "Design", "Code" and "Content", but not now.

Yes the overview page will look _great_, but not now. It's not important. It's much more important to refine the content and get buy in from people first.

Also, it'll be much easier to add "Design", "Code" and "Content" once we've done some presentations/training in the CoPs about the requirements that they have an impact on.

#### An example of why we shouldn't do everything at once

For example, I'm worried that if we just published a TAB guidelines document that indicated that designers were co-responsible for things like "Info and relationships", "Page titled", or "Name role value", they'd feel quite daunted and reject the idea (because this is not something that they currently do or understand.

#### Next steps

I think that we need to get people's input and buy-in about the content of the guidelines summary, and do some training in the CoPs, before we worry about adding things like "Design", "Code" and "Content".

What do you think?

**Comment by robert-kinder** [comment]
As discussed on Slack @jfhector , I think you've summarised the best route forward here. Yes we should call out which sections are applicable to which teams but not yet - there are more important priorities right now.

I just wanted to call out one thing:
> **An example of why we shouldn't do everything at once**
>
>... they'd feel quite daunted and reject the idea (because this is not something that they currently do or understand.

This is a bit of a double-edged sword - calling out that a lot of items specifically refer to Design might be daunting but, equally, having a longer list where it's not immediately obvious what _isn't_ relevant can be daunting as well...

So, a long way of saying, I agree we should shelve this for now but we need to keep it in mind when testing & rolling out to CoPs

**Comment by jfhector** [comment]
I've made progress on this issue as part of a parallel exploration. See https://github.com/theappbusiness/accessibility-guidelines/issues/52
