### ISSUE TITLE
Reading the 1st page, some designers still think that this doesn't apply to native apps

### ISSUE THREAD

**Issue by jfhector** [theappbusiness/accessibility-guidelines#47]
"These are the _web_ content accessibility guidelines, so "app" must mean "a web app".

**Comment by KaneCheshire** [comment]
This is a tough issue to solve nicely, purely based on the name of the WCAG.

Perhaps just some extra info very early on about this at the top of the overview page?

**Comment by jfhector** [comment]
Agree that a line at the top would help, and might suffice (if we keep the introduction very small).

Here's a stab:

> Each guideline applies to native apps as well as browser-based apps, unless stated otherwise.
