### ISSUE TITLE
Some detail pages don't follow the right structure

### ISSUE THREAD

**Issue by jfhector** [theappbusiness/accessibility-guidelines#70]
I've merged the updated detail pages for SC1.3.2-2.4.5. But I haven't double-checked whether the phrasing of the summaries on the overview page still match that on the details page.

This needs checking, and where there are inconsistencies, the phrasing of the summaries on the overview page need updating.

**Comment by taliazdc** [comment]
1.3.2 matches - doesn't follow the What/Why/How format
**1.3.3**  does not match - change overview summary to 

> If you give tips or instructions, don't assume that users can perceive colour, size, shape, sound or the location of elements on screen.



1.3.4 matches
1.3.5 matches
1.4.1 matches
1.4.2 matches - doesn't follow the What/Why/How format
1.4.3 matches - doesn't follow the What/Why/How format
1.4.4 
1.4.5
1.4.6

**Comment by taliazdc** [comment]
1.3.2 matches - doesn't follow the What/Why/How format
1.3.3 does not match - change overview summary to

If you give tips or instructions, don't assume that users can perceive colour, size, shape, sound or the location of elements on screen.

1.3.4 matches
1.3.5 matches
1.4.1 matches
1.4.2 matches - doesn't follow the What/Why/How format
1.4.3 matches - doesn't follow the What/Why/How format
1.4.4 matches 
1.4.5 matches
1.4.10 matches
1.4.11 matches 
1.4.12 matches
1.4.13 matches  - doesn't follow the What/Why/How format

**Comment by jfhector** [comment]
As discussed with Talia, we don't want to follow the 'What, Why, How' structure for the level-2 headings any more.

Here's the list of pages that fail to follow the new structure:
* 1.3.3
* 1.3.4
* 1.3.5
* 1.4.1

**Comment by jfhector** [comment]
I've now updated this in https://github.com/theappbusiness/accessibility-guidelines/pull/76
